import Head from "next/head";
import { useRouter } from "next/router";
import useSWR from "swr";
import Loading from "../../components/Loading";
import GridNews from "../../components/GridNews";
import ContentList from "../../components/ContentList";
import AdvertisementHorizontal from "../../components/AdvertisementHorizontal";
import EmptyResults from "../../components/EmptyResults";
import { domainApi } from "../../requestMethods";

const Articles = () => {
  const { query } = useRouter();
  const cat = query.slug && query.slug[1];
  const subCat = query.slug && query.slug[2];
  const page = query.page || 1;
  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data, error } = useSWR(
    subCat
      ? `${domainApi}/posts?cat=${subCat}&page=${page}&num_results_on_page=10`
      : cat
      ? `${domainApi}/posts?cat=${cat}&page=${page}&num_results_on_page=10`
      : query.q
      ? `${domainApi}/posts/?q=${query.q}&page=${page}&num_results_on_page=10`
      : `${domainApi}/posts?page=${page}&num_results_on_page=10`,
    fetcher
  );
  if (error) return <div className="error">Failed to load</div>;
  if (!data) return <Loading />;

  return (
    <>
      <Head>
        <title>
          {[
            cat === "economy"
                                ? "Phần Mềm"
                                : cat === "innovation"
                                ? "Công Nghệ Web"
                                : cat === "tourism"
                                ? "Chương Trình"
                                : cat === "culture"
                                ? "Máy Photocopy"
                                : cat === "politics"
                                ? "Máy In"
                                : cat === "society"
                                ? "Linh Kiện"
                                : cat === "civil-protection"
                                ? "Máy Photocopy"
                                : cat === "education"
                                ? "Máy In"
                                : cat === "housing"
                                ? "Dòng Mực"
                                : cat === "urban-planning"
                                ? "Khác"
                                : cat === "mobility"
                                ? "Lỗi Thường Gặp"
                                : cat === "environment"
                                ? "Tin Tức"
                                : cat === "sports"
                                ? "Thủ Thuật"
                                : null,
          ]}{" "}
          {subCat &&
            `/ ${[
              subCat === "innovation"
                ? "Công Nghệ Web"
                : subCat === "tourism"
                ? "Chương trình"
                : subCat === "civil-protection"
                ? "Máy Photocopy"
                : subCat === "education"
                ? "Máy In"
                : subCat === "housing"
                ? "Dòng Mực"
                : subCat === "urban-planning"
                ? "Khác"
                : null,
            ]}`}{" "}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.posts.length > 0 ? (
        <>
          <GridNews
            posts={data.posts}
            cat={cat}
            subCat={subCat}
            articles={true}
            page={data.page}
          />
          <ContentList
            posts={data.posts}
            totalPages={data.total_pages}
            page={data.page}
          />
          <AdvertisementHorizontal
            photo="https://res.cloudinary.com/tachibao/image/upload/v1666541043/posts/52432241465_5c8ed1ad36_k_gha4mz_aq2csh.jpg"
            blurhash="LWF~:ss:?bbaWCj[aya{~pWBM{jZ"
            alt="alt"
          />
        </>
      ) : (
        <EmptyResults />
      )}
    </>
  );
};

export default Articles;
