import Head from "next/head";
import React from "react";
import LazyLoadImage from "../components/LazyLoadImage";

const Contacts = () => {
  return (
    <>
      <Head>
        <title>Liên hệ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="contacts">
        <div className="contacts__wrapper">
          <div className="contacts__heading">
            <div className="contacts__title dark:text-slate-200">Lê Chánh Trung:</div>
            <p className="contacts__description dark:text-slate-200">0988607617</p>
          </div>
          <figure className="contacts__image relative pb-[64.3836%]">
            <LazyLoadImage
              photo="https://res.cloudinary.com/dxskael19/image/upload/c_thumb,w_200,g_face/v1680706367/22007859_1452290838159044_8142127994637850023_n_ead93a.jpg"
              blurhash="LKF#|0~B^l9|.TbZaxxbyDI:xWoM"
              alt="alt"
            />
          </figure>
        </div>
      </div>
    </>
  );
};

export default Contacts;
